### ISSUE TITLE
Use CUDA for FaceAnalysis

### ISSUE THREAD

**Issue by henryruhs** [somanchiu/ReSwapper#3]
The insightface dependency has to go in my opinion as this causes lot of issues like:

> libstdc++.so.6: version `GLIBCXX_3.4.32' not found

For the moment, I suggest to use cuda to speed up training:

```python
FaceAnalysis(device='cuda')
```

and for inswapper just:
```
providers = ['CUDAExecutionProvider']
```

**Comment by somanchiu** [comment]
Based on my testing in both Windows and Linux, insightface has no issues. Do you use a Python virtual environment?

As for FaceAnalysis, CUDA has been supported in the code for both training and inference.

**Comment by henryruhs** [comment]
I couldn't find a related commit, so I opened this issue because it's missing in some areas.

**Comment by somanchiu** [comment]
It has always been supported. By default, FaceAnalysis will use CUDA.

**Comment by henryruhs** [comment]
You are correct, the providers args can be removed FaceAnalysis.

Still, there is one InferenceSession missing providers in INSwapper.py:
```
self.session = onnxruntime.InferenceSession(self.model_file, providers=['CUDAExecutionProvider'])
```
I close that issue as we aligned via Discord.
