### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by henryruhs** [somanchiu/ReSwapper#4]
Be so kind and clear the commented out code - you can always restore it via the git history.

**Comment by somanchiu** [comment]
I will, but it's a lower priority. Those codes may inspire someone—who knows?

**Comment by henryruhs** [comment]
Inspire to skip the project...

**Comment by somanchiu** [comment]
LOL

**Comment by somanchiu** [comment]
Maybe move it to somewhere more visible than the GitHub history.

**Comment by henryruhs** [comment]
Thanks
